version: "2"
linters:
  default: none
  enable:
    - ineffassign
    - revive
    - staticcheck
    - unconvert
    - unused
    - usetesting
  settings:
    staticcheck:
      checks:
        - all
        - -SA1019
        - -SA2002
        - ST1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - ineffassign
        path: conversion\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - go.etcd.io
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
