name: Test AMD64
permissions: read-all
on: [push, pull_request]
jobs: 
  test-linux-amd64:
    uses: ./.github/workflows/test_template.yaml
    with:
      targets: "['linux-amd64-unit-4-cpu-race']"
  test-linux-386:
    uses: ./.github/workflows/test_template.yaml
    with:
      targets: "['linux-386-unit-1-cpu']"

  coverage:
    needs:
      - test-linux-amd64
      - test-linux-386
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - run: make test
